const express = require("express");
const app = express();
const cors = require("cors");
const bodyparser = require("body-parser");
const split_router = require("./routes/split_router");
const employee_router = require("./routes/employee_router");
const dashobard_router = require("./routes/dashboard_router");
const deptrouter = require("./routes/department_router");
const jobsRouter = require("./routes/jobs_router");
const reportsRouter = require("./routes/reports_router");
const authRouter = require("./routes/auth_router");
process.env.ORA_SDTZ = "UTC";
app.use(cors());
app.use(express.urlencoded({ extended: false }));
app.use(express.json());
app.use(dashobard_router);
app.use(authRouter);
app.use(split_router);
app.use("/emps", employee_router);
app.use("/dept", deptrouter);
app.use("/job", jobsRouter);
app.use("/report", reportsRouter);

app.listen(3000, "192.168.0.69", () => console.log("listenting on port 3000"));
